package com.iispl.enums;

public enum AccountValidationEnum {

    ACCOUNT_NOT_FOUND,
    FROM_ACCOUNT_NOT_FOUND,
    TO_ACCOUNT_NOT_FOUND,
    FROM_ACCOUNT_INACTIVE,
    TO_ACCOUNT_INACTIVE,
    FROM_ACCOUNT_BLOCKED,
    TO_ACCOUNT_BLOCKED,
    INSUFFICIENT_BALANCE,
    SAME_ACCOUNT_TRANSFER,
    INVALID_ACCOUNT_NUMBER, VALID_ACCOUNT, NOT_ACTIVE, INVALID_ACCOUNT_TYPE, INVALID_ACCOUNT_BALANCE
}